import "reflect-metadata";
import { DataSource } from "typeorm";
import {
  Rol,
  Usuario,
  Facultad,
  ProgramaEducativo,
  Docente,
  Estudiante,
  UsuarioRol,
  Sesion,
  PasswordResetToken,
  TipoPregunta,
  InstrumentoEvaluacion,
  SeccionInstrumento,
  Pregunta,
  OpcionRespuesta,
  PeriodoEvaluacion,
  Evaluacion,
  RespuestaEvaluacion,
} from "../entities";

export const AppDataSource = new DataSource({
  type: "postgres",
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT ?? 5432),
  database: process.env.DB_NAME,
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  ssl: (process.env.DB_SSL ?? "true") === "true" ? { rejectUnauthorized: false } : false,
  synchronize: false,
  logging: false,
  entities: [
    Rol,
    Usuario,
    Facultad,
    ProgramaEducativo,
    Docente,
    Estudiante,
    UsuarioRol,
    Sesion,
    PasswordResetToken,
    TipoPregunta,
    InstrumentoEvaluacion,
    SeccionInstrumento,
    Pregunta,
    OpcionRespuesta,
    PeriodoEvaluacion,
    Evaluacion,
    RespuestaEvaluacion,
  ],
});
